### ISSUE TITLE
Migrate TxtToHtmlEditable.

### ISSUE THREAD

**Issue by alaneckhardt** [seznam/flexp#12]
Editable Txt is sometime useful for example to edit the description of the experiment. It is quite convenient to do it directly from flexp than on the file system level.

**Comment by tomasprinda** [comment]
It is in [TxtToHtml](https://github.com/seznam/flexp/blob/876ca0e3f8bd65b82af4b49591afe73aa3491f25/flexp/browser/html/generic.py#L30) as a parameter `editable`, default to `True`.

**Comment by alaneckhardt** [comment]
You're right! I remember the discussion now. Thanks!
