### ISSUE TITLE
Wanted to add tests in CI (Travis.ci) but I probably have to be member of the organization

### ISSUE THREAD

**Issue by tivvit** [seznam/flexp#13]
@ondras @dmvk can you help pls?

**Comment by dmvk** [comment]
cc @prcek

**Comment by ondras** [comment]
Looks like my help is no longer required here .)

**Comment by tivvit** [comment]
ping @prcek 
Or maybe @alaneckhardt can help?

**Comment by tivvit** [comment]
Solved w @ondras now it seems to work. 
Closing
