### ISSUE TITLE
Print error to log

### ISSUE THREAD

**Issue by tomasprinda** [seznam/flexp#26]
If the script ends with an Exception it might be useful to print to `log.txt` the text that is printed to stderr. 
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    raise Exception("Text of exception")
Exception: Text of exception
```

**Comment by alaneckhardt** [comment]
I agree, but unfortunately I don't have much time to work on flexp now. I hope January will be a bit calmer.
